apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-secret-rotation
  namespace: vault
spec:
  schedule: "0 0 * * 0" # Weekly rotation
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault-rotation
          containers:
          - name: rotation
            image: vault:1.12.0
            command: [ "/bin/sh", "-c" ]
            args:
            - |
              vault login -method=kubernetes \
                role=rotation \
                jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

              # Rotate database credentials
              vault write -force database/rotate-root/postgresql
              vault write -force database/rotate-credentials/app-user

              # Rotate API keys
              vault write -force secret/data/huggingface/config \
                @/vault/secrets/new-credentials.json

              # Notify rotation completion
              curl -X POST ${SLACK_WEBHOOK_URL} \
                -H 'Content-Type: application/json' \
                -d '{"text":"Secret rotation completed successfully"}'
            env:
            - name: VAULT_ADDR
              value: "http://vault:8200"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: url
            volumeMounts:
            - name: new-credentials
              mountPath: /vault/secrets
          volumes:
          - name: new-credentials
            secret:
              secretName: new-credentials-template
          restartPolicy: OnFailure
