apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-runner-backup
  namespace: gitlab
spec:
  schedule: "0 4 * * *" # Daily at 4 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: runner-backup
            image: alpine:3.14
            command:
            - /bin/sh
            - -c
            - |
              BACKUP_DIR="/backup/gitlab-runner/$(date +%Y%m%d)"
              mkdir -p $BACKUP_DIR
              cp -r /etc/gitlab-runner/* $BACKUP_DIR/
              tar czf $BACKUP_DIR.tar.gz $BACKUP_DIR
              rm -rf $BACKUP_DIR
            volumeMounts:
            - name: runner-config
              mountPath: /etc/gitlab-runner
              readOnly: true
            - name: backup-store
              mountPath: /backup
          volumes:
          - name: runner-config
            hostPath:
              path: /etc/gitlab-runner
          - name: backup-store
            persistentVolumeClaim:
              claimName: backup-store
          restartPolicy: OnFailure
