apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-config
  namespace: vault
data:
  setup.sh: |
    #!/bin/sh
    vault auth enable kubernetes

    vault write auth/kubernetes/config \
      kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
      token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
      kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      issuer="https://kubernetes.default.svc.cluster.local"

    # Create policies
    vault policy write app-policy - <<EOF
    path "secret/data/huggingface/*" {
      capabilities = ["read"]
    }
    path "secret/data/common/*" {
      capabilities = ["read"]
    }
    EOF

    # Create Kubernetes auth roles
    vault write auth/kubernetes/role/huggingface-app \
      bound_service_account_names=huggingface-app \
      bound_service_account_namespaces=frontend-* \
      policies=app-policy \
      ttl=1h
