apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: registry-access
  namespace: infrastructure
spec:
  podSelector:
    matchLabels:
      app: harbor
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: frontend
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: gitlab
    ports:
    - protocol: TCP
      port: 443
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: metrics
