expose:
  type: ingress
  tls:
    enabled: true
  ingress:
    hosts:
      core: registry.local
    annotations:
      kubernetes.io/ingress.class: traefik

persistence:
  enabled: true
  size: 50Gi

harborAdminPassword: "Harbor12345"

core:
  replicas: 1
  secret: changeme

chartmuseum:
  enabled: false

notary:
  enabled: false

trivy:
  enabled: true
  replicas: 1

database:
  type: internal
  internal:
    size: 10Gi
