apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: huggingface-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/your-project.git'
    path: helm/huggingface-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
