apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.local/your-project/huggingface-app.git
  username: argocd-sync
  password: ${GITLAB_TOKEN}
