server:
  config:
    url: https://argocd.local
    oidc.config: |
      name: Keycloak
      issuer: https://auth.local/realms/infrastructure
      clientID: argocd
      clientSecret: $argo-oauth-secret
      requestedScopes: ["openid", "profile", "email", "groups"]
    webhookSecret: ${WEBHOOK_SECRET}
    repositories: |
      - url: https://gitlab.local/your-project/huggingface-app.git
        type: git
        insecure: false
        githubAppId: ""
        githubAppInstallationId: ""
        githubAppEnterpriseBaseUrl: ""
        githubAppPrivateKey: ""
        enableLfs: false
        proxy: ""
        ref: ""

  rbac:
    policy.csv: |
      g, OpsTeam, role:admin
      g, DevTeam, role:readonly
      g, QATeam, role:readonly

  ingress:
    enabled: true
    hosts:
    - argocd.local
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: "internal-ca-issuer"
      kubernetes.io/tls-acme: "true"
    tls:
    - secretName: argocd-tls
      hosts:
      - argocd.local

  additionalApplications:
  - name: environments
    namespace: argocd
    project: default
    source:
      repoURL: https://gitlab.local/your-project/huggingface-app.git
      targetRevision: HEAD
      path: argocd
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        selfHeal: true
        prune: true

repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
  volumeMounts:
  - mountPath: /custom-tools
    name: custom-tools
