apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca-issuer
spec:
  ca:
    secretName: internal-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretName: wildcard-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.local"
  dnsNames:
  - "*.local"
  - "*.monitoring.local"
  - "*.frontend.local"
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-cert
  namespace: monitoring
spec:
  secretName: monitoring-tls
  duration: 2160h
  renewBefore: 360h
  commonName: monitoring.local
  dnsNames:
  - monitoring.local
  - prometheus.local
  - grafana.local
  - alertmanager.local
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
