apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: huggingface-app-development
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/your-project/huggingface-app.git'
    targetRevision: develop
    path: helm/huggingface-app
    helm:
      valueFiles:
      - values.yaml
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
