apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: huggingface-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/your-project/huggingface-app.git'
    targetRevision: HEAD
    path: helm/huggingface-app
    helm:
      valueFiles:
      - values.yaml
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: false # Require manual sync for production
